config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root :to => "articles#index"

match '/author/:id', :to => 'authors#show',  :as => :author,  :via => :get

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_author!, :except => [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('created_at DESC')
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    set_meta_tags title: @article.title,
            site: 'Pine Blog',
            reverse: true,
            description: @article.body.truncate(300),
            twitter: {
              card: "summary",
              title: @article.title,
              description:  @article.body.truncate(300),
            },
            og: {
              title:    @article.title,
              description: @article.body.truncate(300),
              type:     'website',
              url:      article_url(@article),
            }
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    unless @article.author == current_author || current_author.present?
      return render text: "Not Allowed", status: :forbidden
  end
end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_author.articles.create(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
        format.js
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :published, :id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="title h1">
      <%= f.text_area :title , class: "h1 editable", remote: true,label: false,
      placeholder: "New Article"%>
    </div>

    <%= f.text_area :body , class: "editable", remote: true, label: false,
    placeholder:"Tell your story..." %>

  <div class="field">
    <i class="fa fa-globe" aria-hidden="true"></i>
    <%= f.input :published, as: :boolean %>
  </div>

  <div class="entry_actions">
    <%= f.submit %>
  </div>

<% end %>

<script>
  var editor = new MediumEditor('.editable', {
    // options go here
  });
</script>

app/views/articles/_no-articles.html.erb
<div class="nocontent">
  <i class="fa fa-file-text notice" aria-hidden="true"></i>
  <h3>No Articles</h3>
  <small>This site doesn't have any articles listed! <%= link_to "Create a new
  one here", new_article_path %>
  </small>
</div>

app/views/articles/edit.html.erb
<div class="container" id="page-wrap">
  <div id="article_expanded" class="col-md-8">
  <%= render 'form', article: @article %>
    <%= link_to 'Show', @article %> |
    <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container" id="page-wrap">
  <div class="col-md-12">
  <h3>Articles</h3>


<div class="col-md-12">
  <% unless @articles.blank? %>
  <% @articles.each do |article| %>
<div class="article_entry">
        <% if article.published? %>
        <h3><%= link_to article.title.html_safe, article %></h3>
        <div id="author_info">
          <%= link_to article.author, class: :"author_link" do %>
            <%= image_tag article.author.avatar.article_thumb, class: "avatar" %>
            <%= article.author.name %>
          <% end %>
        </div>
        <small class="time"> <i class="fa fa-clock-o"></i> <%= article.created_at.to_date.iso8601  %></small>
        <p><%= strip_tags(article.body).truncate(300) %></p>
</div>
        <% end %>
  <% end %>
<% else %>
<%= render "no-articles" %>
<% end %>
</div>

    </div>

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container" id="page-wrap">
    <div id="article_expanded" class="col-md-8">
    <%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container" id="page-wrap">
  <div id="article_expanded" class="col-md-8">
    <h1 class="title">
      <%= @article.title.html_safe %>
    </h1>

    <div id="author_info">
      <%= link_to @article.author, class: :"author_link" do %>
        <%= image_tag @article.author.avatar.article_thumb, class: "avatar" %>
        <%= @article.author.name %>
      <% end %>
    </div>

    <small class="time"> <i class="fa fa-clock-o"></i>
      <%= @article.created_at.to_date.iso8601  %>
    </small>

<% if current_author && current_author == @article.author %>
    <div class="entry_actions">
      <%= link_to edit_article_path(@article) do %>
      <i class="fa fa-pencil"></i>
        <% end %>
      <%= link_to @article, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="fa fa-close"></i>
      <% end %>
    </div>
    <% end %>

      <%= @article.body.html_safe %>
  </div>
</div>