config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root :to => "articles#index"

match '/author/:id', :to => 'authors#show',  :as => :author,  :via => :get

end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <p>Powered by <b>Pine</b></p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md fixed-top bg-faded">

<div class="nav-container">
  <a class="navbar-brand" href="/">Pine</a>

<div id="user_menu">
  <div class="btn-group">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <% if author_signed_in? %>
      <%= image_tag current_author.avatar.article_thumb, class: "sidebar_avatar" %>
      <%= current_author.name %>
      <% else %>
      <i class="fa fa-user-circle" aria-hidden="true"></i>
      Author
      <% end %>
    </button>
    <div class="dropdown-menu dropdown-menu-right">


      <% if author_signed_in? %>
      <%= link_to "New Article", new_article_path(current_author),
      class: "dropdown-item" %>
      <%= link_to "My Profile", author_path(current_author),
      class: "dropdown-item" %>
      <%= link_to "Edit Profile", edit_author_registration_path,
      class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", destroy_author_session_path,
        class: "dropdown-item", method: :delete %>

        <% else %>
        <%= link_to "Sign In", new_author_session_path,
        class: "dropdown-item" %>
      <% end %>

    </div>
  </div>
</div>
</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pine</title>
    <%= csrf_meta_tags %>
    <%= display_meta_tags %>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>